version: '3.4'

networks:
  deployment-app:
    driver: bridge

services:

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    environment:
      - USER=${user_fe}
      - env=${env}
      - VITE_API_SERVER=${api_for_conect}
    container_name: ${container_fe}
    image: ${image_fe}
    networks:
      - ${net_day5}
    ports:
      - "${port_fe}"

  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - USER=${user_api}
      - env=${env}
    container_name: ${container_api}
    image: ${image_api}
    networks:
      - ${net_day5}
    ports:
      - "${port_api}"
