- name: Run app
  hosts: all
  gather_facts: true
  become: yes
  tasks:
    # Copy zip file
    - name: Copy zip files from local to remote ...
      copy:
        src: /home/duongtn1512/Terraform/ansible/App.tar.gz  
        dest: /home/ubuntu 
    # Unzip the tar files
    - name: Unziping App.tar.gz ...
      shell: tar -xzvf /home/ubuntu/App.tar.gz -C /home/ubuntu
    # Run a Docker Compose
    - name: Run Docker Compose ...
      shell: docker-compose -f /home/ubuntu/App/compose.yaml up -d
      args:
        chdir: /home/ubuntu/App